### ISSUE TITLE
Please add the progress meter in the script

### ISSUE THREAD

**Issue by unixbhaskar** [pimlie/ubuntu-mainline-kernel.sh#1]
While downloading big file people should be aware that something is happening in front of their eyes instead of in the background. A progress bar on the terminal would nice ...I mean fetching can be done in the foreground too..more visible stuff

like in dd or pv

--status=progress

**Comment by pimlie** [comment]
Unfortunately this seems not really easy to do because I use `cat /dev/tcp` to download files instead of a dependency like wget or curl. Also it seems not really easy to run two functions in parallel in bash (one for downloading, one for progress), it will add quite a bit of complexity.

If you have an easy suggestion for the implementation please feel free to comment or add a PR :)

**Comment by pimlie** [comment]
Hi, I just pushed some changes and now there should be a progress indicator when download the debs. Hope this helps!

**Comment by unixbhaskar** [comment]
Thanks a bunch!

**Comment by unixbhaskar** [comment]
Well, spot an small glitch...

root@ElementaryOSLinux:/usr/src# ./ubuntu_mainline_kernel_build.sh -c
./ubuntu_mainline_kernel_build.sh: line 544: syntax error near unexpected token `else'
./ubuntu_mainline_kernel_build.sh: line 544: `        else'

**Comment by pimlie** [comment]
Did you change any of the config options at the top? Eg what is your `debug_target` or did you change the path to `sudo`?
