### ISSUE TITLE
Does not detect latest installed RC on 20.04

### ISSUE THREAD

**Issue by f-s** [pimlie/ubuntu-mainline-kernel.sh#33]
Hello,

this is the output I get running the latest RC **already**:

> ./ubuntu-mainline-kernel.sh -c --rc -d
> Finding latest version available on kernel.ubuntu.com: v5.7.0-rc5
> Finding latest installed version: v5.7.0
> A newer kernel version (v5.7.0-rc5) is available

Thanks and best regards,

f-s-e

**Comment by gothicVI** [comment]
That's expected as the rc-tag is not part of the internal package name. The kernel ist identified as `v5.7.0` which should also be the result of `uname -r`.

**Comment by f-s** [comment]
> That's expected as the rc-tag is not part of the internal package name. The kernel ist identified as `v5.7.0` which should also be the result of `uname -r`.

But how can a newer kernel version be available, albeit its not available?

**Comment by gothicVI** [comment]
As I explained: The rc kernel do not have rc in the package name. Thus any rc kernel will present itself to the system as a non-rc kernel, i.e., `v5.7.0-rc5` will always show up as `v5.7.0`.
When you then search for newer versions the script sees `v5.7.0` installed and since you call the script with the `--rc` flag it finds a non-installed version, namely `v5.7.0-rc5`.

**Comment by pimlie** [comment]
Have created a separate tracking issue for improving rc support, will close this issue in favor of the linked one

**Comment by f-s** [comment]
thanks!
