### ISSUE TITLE
Abort, the amd64 build has not succeeded

### ISSUE THREAD

**Issue by dacorsa** [pimlie/ubuntu-mainline-kernel.sh#38]
Hi,
On ubuntu Focal, i receive this error after installed libssl1.1, how can i i solve?

08:30:40 root@NanoKDE /app/ubuntu-mainline-kernel.sh master# uname -a ; ubuntu-mainline-kernel.sh -i
Linux NanoKDE 5.7.1-050701-lowlatency #202006071230 SMP PREEMPT Sun Jun 7 12:35:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
Finding latest version available on kernel.ubuntu.com
Latest version is: v5.7.2, continue? (y/N) 
Abort, the amd64 build has not succeeded
08:30:55 root@NanoKDE /app/ubuntu-mainline-kernel.sh master# aptinstallati |grep 1.1.1f-1ubuntu2

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

libssl-dev/focal,focal,now 1.1.1f-1ubuntu2 amd64 [installato]
libssl1.1/focal,focal,now 1.1.1f-1ubuntu2 amd64 [installato]
libssl1.1/focal,focal,now 1.1.1f-1ubuntu2 i386 [installato, automatico]
openssl/focal,focal,now 1.1.1f-1ubuntu2 amd64 [installato]
08:31:09 root@NanoKDE /app/ubuntu-mainline-kernel.sh master#

**Comment by gothicVI** [comment]
They changed the `success` string as reported here: https://github.com/pimlie/ubuntu-mainline-kernel.sh/issues/37.
How though is your report related to `libssl1.1`?

**Comment by dacorsa** [comment]
before i installing libssl i installed successfully the version 5.7.1-050701-lowlatency, have you upgrade to 5.7.2 amd64 version lowlatency?
Thanks

**Comment by gothicVI** [comment]
No, I have not due to the obvious fix that's needed for the script.
The error message clearly tells that `Abort, the amd64 build has not succeeded` which it why the script wouldn't download or install anything. That's a sensible safety measure.
However, as pointed out here: https://github.com/pimlie/ubuntu-mainline-kernel.sh/issues/37, Ubuntu changed their naming scheme of reporting success and thus the script does recognize the build as failed.
All of this is independent from the SSL library you mentioned.
We'll just need to wait for an update of the script. If you have time you might create a PR as it looks like it should be an easy fix.

**Comment by pimlie** [comment]
@dacorsa Could you please download & try the latest version and see if it works for you?

**Comment by MohakChugh** [comment]
I'm Facing the exact same issue. I updated the script again and found this error:
![Screenshot from 2020-06-13 23-49-37](https://user-images.githubusercontent.com/33135218/84576222-acac5780-add0-11ea-9988-d037607cd84a.png)

**Comment by dacorsa** [comment]
yes, me too, now the error is:
Expect to download 6 files but found 2

**Comment by hcarrega** [comment]
same error here

**Comment by robinpaulson** [comment]
see #40

**Comment by hcarrega** [comment]
> see #40 

Thanks

**Comment by pimlie** [comment]
Thanks for the updates, should be fixed with latest version
