### ISSUE TITLE
While removing the kernel ..it should be front of the eyes

### ISSUE THREAD

**Issue by unixbhaskar** [pimlie/ubuntu-mainline-kernel.sh#4]
Not in the background ..that is very very important ...the output of removal/purge should be visible...so end user can see what is happening!

**Comment by pimlie** [comment]
This script provides an abstraction for installing and removing packages and I specifically wanted to hide the default output because I dont care about that output. I only care whether the purge was successful or not :)

If you really want to see the output you could probably change your debug_target to a local file, run the script with the option `--yes` in the background and tail your debug_target:

```bash
$ ubuntu_mainline_kernel.sh --yes &; tail ./ubuntu-mainline-kernel.log -f
```
