### ISSUE TITLE
Check to see if another kernel is installed, rather than asking the user

### ISSUE THREAD

**Issue by robinpaulson** [pimlie/ubuntu-mainline-kernel.sh#50]
After I do "ubuntu-mainline-kernel.sh -u" and select the kernel to uninstal, the script asks:

"Do you still have another kernel installed? (y/N)"

I'm sure we could check for another kernel installed, either from ubuntu-mainline-kernel.sh or from other (apt) sources. If there isn't a positive from either of those sources, *then* ask if there is another kernel installed.

Yes, it's minor, it's a small usability thing, not at all high priority.

**Comment by pimlie** [comment]
Altho this makes somewhat sense, I am not gonna add support for this. The reason is that I feel you need to know yourself if you have a kernel. Just dont want to have the risk that the script has a bug and somehow thinks there is still a kernel installed while there isnt.

Also, if you are using this script and you dont know for sure if you still have another kernel installed then you should probably not be using this script in the first place cause it seems that you dont rly know what you are doing... ;)
