### ISSUE TITLE
[bug] or [syntax error] on line 725 $sudo instead of sudo make script not to install upgrading kernel

### ISSUE THREAD

**Issue by harlock59300** [pimlie/ubuntu-mainline-kernel.sh#62]
[bug] or [syntax error] on line 725 $sudo instead of sudo make script not to install upgrading kernel

**Comment by gothicVI** [comment]
That's very little information. Are you running the latest version of the script? What's the command you're calling? What's the exact output? How does line 725 look like in its entirety?

**Comment by harlock59300** [comment]
the complete line is "$sudo dpkg -i "${debs[@]}" >$debug_target 2>&1"

i may be wrong but is be "sudo dpkg -i "${debs[@]}" >$debug_target 2>&1"

**Comment by gothicVI** [comment]
Take a look at https://github.com/pimlie/ubuntu-mainline-kernel.sh/blob/master/ubuntu-mainline-kernel.sh#L26 to https://github.com/pimlie/ubuntu-mainline-kernel.sh/blob/master/ubuntu-mainline-kernel.sh#L28.
There, the variable `sudo` is set if wanted by the user. Otherwise, call the script using the command `sudo` yourself.
Does that help?
